function generateContent(task) {
  return `// Generated by Spec-to-Ship
// Task: ${task.description}

function generatedFeature() {
  return '${task.description}';
}

module.exports = { generatedFeature };
`;
}

async function generateAll(tasks) {
  return tasks.map(task => ({
    taskId: task.id,
    targetFile: task.targetFile,
    content: generateContent(task)
  }));
}

module.exports = {
  generateAll
};