const { Octokit } = require('octokit');

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

const owner = process.env.GITHUB_OWNER;
const repo = process.env.GITHUB_REPO;
const baseBranch = process.env.GITHUB_BASE_BRANCH || 'main';

async function getBaseSHA() {
  const { data } = await octokit.rest.repos.getBranch({
    owner,
    repo,
    branch: baseBranch
  });

  return data.commit.sha;
}

async function createBranch(branchName, sha) {
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha
  });
}

async function commitFile(branchName, filePath, content) {
  let fileSHA;

  try {
    const { data } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path: filePath,
      ref: branchName
    });

    fileSHA = data.sha;
  } catch {
    fileSHA = undefined;
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: `feat: generate ${filePath} via Spec-to-Ship`,
    content: Buffer.from(content).toString('base64'),
    branch: branchName,
    ...(fileSHA ? { sha: fileSHA } : {})
  });
}

async function openPR(branchName, title, body) {
  const { data } = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branchName,
    base: baseBranch
  });

  return data.html_url;
}

async function createPullRequest(outputs, prDescription) {
  const branchName = `spec-to-ship/generated-${Date.now()}`;
  const baseSHA = await getBaseSHA();

  await createBranch(branchName, baseSHA);

  for (const output of outputs) {
    await commitFile(branchName, output.targetFile, output.content);
  }

  const prUrl = await openPR(
    branchName,
    prDescription.title || 'feat: generated feature',
    prDescription.body || 'Generated by Spec-to-Ship.'
  );

  return { prUrl };
}

module.exports = {
  createPullRequest
};